### ISSUE TITLE
[api] Mapear tecnologias para implementação da API

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/infra#4]
Requisitos:
- Baixa latência
- Fácil de manter
- Python
- Gestão de acesso --> escolher tipos de planos de monetização
- Gestão de banda --> bloquear pessoas que fazem requisições demais

apigee --> google cloud
graphql

**Comment by vncsna** [comment]
Talvez seja necessário alterar algo, mas parcialmente resolvido em [GDocs](https://docs.google.com/spreadsheets/d/1Wc-trdEdW-CClgBvzQtpzJKbbWKSXoVIqMCywkaOxvE/edit#gid=0)
