### ISSUE TITLE
Diminuir o limite de tamanho de tabelas disponíveis no one-click-download

### ISSUE THREAD

**Issue by rdahis** [basedosdados/infra#5]
Hoje não sabemos exatamente qual é esse limite.

Proposta de máximo (já zipado): 80mb.

**Comment by rdahis** [comment]
Prioridade esse gente. O one-click-download tá muito caro para a BD. E deve ser fácil de resolver. Podem olhar @polvoazul @vncsna?

**Comment by rdahis** [comment]
Ideia alternativa do @JoaoCarabetta: passar o one-click-download para o Cloud Fare, que não cobra por data egress.

https://blog.cloudflare.com/introducing-r2-object-storage/
https://www.cloudflare.com/bandwidth-alliance/
https://blog.cloudflare.com/aws-egregious-egress/

**Comment by polvoazul** [comment]
Vou dar uma olhada! acho q mudar pra esse cloudfare seria o ideal mesmo!

**Comment by polvoazul** [comment]
![image](https://user-images.githubusercontent.com/1513181/136590116-7aa18090-5793-477f-9aa0-f9055cb2f6c1.png)
Fuck! Ninguem olha as letras miudas... :( :( @JoaoCarabetta

**Comment by polvoazul** [comment]
entrei no wishlist. Mas por ora, vou limitar pra 80MB

**Comment by rdahis** [comment]
@polvoazul conseguiu avançar aqui? O que falta, em termos de bullet points?
