### ISSUE TITLE
[infra] Revisar 1-click download

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/infra#6]
- [x] Rever geração dos valores para os campos `uncompressed_file` e `compressed_file`: estao de fato mostrando os tamanhos dos arquivos no BQ?
- [x] Não exibir botão no FE se tamanho zipado for maior que 100 MB 
- [x] Jogar esse código para o website
- [x] Exibir no FE os tamanhos zipado e normal (passar para website quando tiver pronto @AldemirLucas )

**Comment by rdahis** [comment]
@lucascr91 ver aqui por favor. Vale fechar esse issue perdido aqui e passar as ideias para issues novos (tipo o zip já vir com o dicionário e metadados).

**Comment by lucascr91** [comment]
Sim. Vamos decompor essa issue em outras e passar para o repositório de pipelines. Ver também: https://github.com/basedosdados/website/issues/222
